package com.wokgui.schedulewidget;

final class PersonalizationUi2 {
    private PersonalizationUi2() {}

    static String script() {
        return """
            (function(){
              try{
                if(window.__personalizationV2){if(window.refreshPersonalizationV2)window.refreshPersonalizationV2();return;}
                window.__personalizationV2=true;

                const THEMES={
                  blue:{n:{fr:'Bleu',en:'Blue',de:'Blau'},a:'#0877f9',d:'#075fae',s:'#d9eafb',bg:'#f6f8fb',ink:'#111936',m:'#68738a',line:'#dce3eb'},
                  teal:{n:{fr:'Turquoise',en:'Teal',de:'Türkis'},a:'#00897b',d:'#00695c',s:'#ddf4f0',bg:'#f5f9f8',ink:'#102b28',m:'#60736f',line:'#d7e6e3'},
                  violet:{n:{fr:'Violet',en:'Violet',de:'Violett'},a:'#6750a4',d:'#4f378b',s:'#ede7f6',bg:'#f8f6fb',ink:'#241b35',m:'#6c6476',line:'#e1dbe9'},
                  green:{n:{fr:'Vert',en:'Green',de:'Grün'},a:'#2e7d32',d:'#1b5e20',s:'#e3f3e4',bg:'#f6faf6',ink:'#172b19',m:'#617162',line:'#d9e7da'},
                  amber:{n:{fr:'Ambre',en:'Amber',de:'Amber'},a:'#ef6c00',d:'#bf4e00',s:'#ffebd8',bg:'#fff9f4',ink:'#352015',m:'#75685e',line:'#eadfd5'}
                };
                const I={
                  fr:{settings:'Réglages',appFont:'Taille du texte de l’application',widgetFont:'Taille du texte du widget',language:'Langue',theme:'Thème',reset:'Réinitialiser',close:'Fermer',appPreview:'Aperçu application',widgetPreview:'Aperçu widget',title:'Emploi du temps',thisWeek:'Cette semaine',week:'Semaine',today:'Aujourd’hui',edit:'Modifier',progress:'Avancement',importPhoto:'Importer une photo d’emploi du temps',breaks:'Noms des interruptions',slots:'Horaires des 7 heures',add:'Ajouter un cours',gap:'Trou',lunch:'Pause de midi',badge:'Badge',weekPreview:'Aperçu semaine',period:'Heure de cours',group:'Classe / groupe',room:'Salle',del:'Supprimer',cancel:'Annuler',save:'Enregistrer',current:'En cours',courses:'cours'},
                  en:{settings:'Settings',appFont:'App text size',widgetFont:'Widget text size',language:'Language',theme:'Theme',reset:'Reset',close:'Close',appPreview:'App preview',widgetPreview:'Widget preview',title:'Timetable',thisWeek:'This week',week:'Week',today:'Today',edit:'Edit',progress:'Progress',importPhoto:'Import a timetable photo',breaks:'Break names',slots:'7 period times',add:'Add a class',gap:'Free period',lunch:'Lunch break',badge:'Badge',weekPreview:'Week preview',period:'Class period',group:'Class / group',room:'Room',del:'Delete',cancel:'Cancel',save:'Save',current:'In class',courses:'classes'},
                  de:{settings:'Einstellungen',appFont:'Textgröße der App',widgetFont:'Textgröße des Widgets',language:'Sprache',theme:'Design',reset:'Zurücksetzen',close:'Schließen',appPreview:'App-Vorschau',widgetPreview:'Widget-Vorschau',title:'Stundenplan',thisWeek:'Diese Woche',week:'Woche',today:'Heute',edit:'Bearbeiten',progress:'Fortschritt',importPhoto:'Stundenplan-Foto importieren',breaks:'Bezeichnungen der Unterbrechungen',slots:'Zeiten der 7 Stunden',add:'Stunde hinzufügen',gap:'Freistunde',lunch:'Mittagspause',badge:'Badge',weekPreview:'Wochenübersicht',period:'Unterrichtsstunde',group:'Klasse / Gruppe',room:'Raum',del:'Löschen',cancel:'Abbrechen',save:'Speichern',current:'Läuft',courses:'Stunden'}
                };
                let S={appFontScale:1,widgetFontScale:1,language:'fr',theme:'blue'};
                try{const r=window.AndroidSchedule&&AndroidSchedule.loadUiSettings?AndroidSchedule.loadUiSettings():localStorage.getItem('edt-ui-settings');if(r)S=Object.assign(S,JSON.parse(r));}catch(e){}
                const lg=()=>['fr','en','de'].includes(S.language)?S.language:'fr',T=()=>I[lg()],TH=()=>THEMES[S.theme]||THEMES.blue,cl=v=>Math.max(.8,Math.min(1.4,Number(v)||1));
                const tx=(e,v)=>{if(e&&e.textContent!==v)e.textContent=v};
                function save(){S.appFontScale=cl(S.appFontScale);S.widgetFontScale=cl(S.widgetFontScale);const raw=JSON.stringify(S);try{if(window.AndroidSchedule&&AndroidSchedule.saveUiSettings)AndroidSchedule.saveUiSettings(raw);else localStorage.setItem('edt-ui-settings',raw)}catch(e){}}

                const st=document.createElement('style');st.textContent=`
                  .header{position:relative!important;background:linear-gradient(135deg,var(--pa),var(--pd))!important}
                  #settingsBtn{position:absolute;right:10px;bottom:12px;width:36px;height:36px;border:0;border-radius:18px;background:#ffffff25;color:#fff;font-size:20px;padding:0}
                  .currentWeek{background:var(--ps)!important;color:var(--pd)!important}.currentWeek b{color:var(--pa)!important}.weekTab.active,.btn.primary{background:var(--pa)!important;border-color:var(--pa)!important}.dayTab.active{background:linear-gradient(135deg,var(--pa),var(--pd))!important;border-color:var(--pa)!important}.timeline>span{background:var(--pa)!important}.timelineHead strong,.count,.addBtn{color:var(--pa)!important}.addBtn{border-color:var(--pa)!important}.todayCourse.current:before{background:var(--pa)!important}.badge:not(.gap):not(.lunch){background:var(--pa)!important}
                  #settingsModal2{position:fixed;inset:0;z-index:100;background:#0b17386b;display:none;align-items:flex-end}#settingsModal2.show{display:flex}#settingsSheet2{width:100%;max-width:780px;margin:auto;background:#fff;border-radius:18px 18px 0 0;padding:14px 14px calc(16px + env(safe-area-inset-bottom));max-height:88vh;overflow:auto;color:#111936}.shead{display:flex;align-items:center;justify-content:space-between}.shead h2{margin:0;font-size:1.08rem}.sx{border:0;background:#eef2f6;border-radius:50%;width:32px;height:32px;font-size:18px}.sg{border:1px solid #dde4ec;border-radius:10px;padding:10px;margin-top:9px}.stt{font-weight:800;font-size:.82rem;margin-bottom:7px}.sr{display:flex;align-items:center;gap:8px}.sr input{width:100%;accent-color:var(--pa)}.sv{min-width:45px;text-align:right;font-weight:800;color:var(--pa);font-size:.78rem}.slang{width:100%;padding:9px;border:1px solid #d8e0e8;border-radius:8px;background:#fff}.tg{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:6px}.tc{border:2px solid transparent;border-radius:9px;padding:5px 3px;background:#f7f8fa}.tc.on{border-color:var(--pa);background:var(--ps)}.sw{display:block;height:25px;border-radius:6px}.tn{display:block;font-size:.58rem;font-weight:800;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pv{display:grid;grid-template-columns:1fr 1fr;gap:8px}.pl{font-size:.67rem;font-weight:800;color:#657087;margin-bottom:4px}.mini{border:1px solid #dce3eb;background:#fff;overflow:hidden}.appTop{height:20px;background:linear-gradient(90deg,var(--pa),var(--pd));color:#fff;font-size:7px;font-weight:800;display:flex;align-items:center;justify-content:center}.miniBody{padding:5px}.ml{height:6px;border-radius:4px;background:var(--ps);margin:3px}.ml.a{width:65%;background:var(--pa)}.wid{background:var(--ps);padding:5px}.wt{font-size:7px;font-weight:900;color:var(--pink)}.wm{font-size:6px;color:var(--pm);margin-top:2px}.wb{height:4px;background:#d7e0e8;margin-top:4px}.wb i{display:block;width:56%;height:100%;background:var(--pa)}.sa{display:flex;justify-content:space-between;margin-top:12px}.sab{padding:9px 12px;border:1px solid #d6dee7;border-radius:8px;background:#fff;font-weight:800}.sab.p{background:var(--pa);border-color:var(--pa);color:#fff}@media(max-width:380px){.tg{grid-template-columns:repeat(3,1fr)}}`;
                document.head.appendChild(st);

                const h=document.querySelector('.header');if(h&&!document.getElementById('settingsBtn')){const b=document.createElement('button');b.id='settingsBtn';b.type='button';b.textContent='⚙';h.appendChild(b)}
                const m=document.createElement('div');m.id='settingsModal2';m.innerHTML=`<div id="settingsSheet2"><div class="shead"><h2 id="sTitle"></h2><button id="sX" class="sx">×</button></div><div class="pv"><div><div id="pApp" class="pl"></div><div class="mini"><div id="miniTitle" class="appTop"></div><div class="miniBody"><div class="ml a"></div><div class="ml"></div><div class="ml"></div></div></div></div><div><div id="pWidget" class="pl"></div><div class="mini"><div class="wid"><div class="wt">4G1 ALL · 4G2 ALL</div><div class="wm">08:00 - 09:00</div><div class="wb"><i></i></div></div></div></div></div><div class="sg"><div id="afT" class="stt"></div><div class="sr"><input id="af" type="range" min="80" max="140" step="5"><div id="afV" class="sv"></div></div></div><div class="sg"><div id="wfT" class="stt"></div><div class="sr"><input id="wf" type="range" min="80" max="140" step="5"><div id="wfV" class="sv"></div></div></div><div class="sg"><div id="lgT" class="stt"></div><select id="lg" class="slang"><option value="fr">Français</option><option value="de">Deutsch</option><option value="en">English</option></select></div><div class="sg"><div id="thT" class="stt"></div><div id="tg" class="tg"></div></div><div class="sa"><button id="sReset" class="sab"></button><button id="sDone" class="sab p"></button></div></div>`;document.body.appendChild(m);

                function theme(){const q=TH();[['--pa',q.a],['--pd',q.d],['--ps',q.s],['--pink',q.ink],['--pm',q.m],['--blue',q.a],['--blue2',q.d],['--teal',q.a],['--ink',q.ink],['--muted',q.m],['--line',q.line],['--soft',q.s],['--bg',q.bg]].forEach(x=>document.documentElement.style.setProperty(x[0],x[1]));document.body.style.background=q.bg;document.querySelectorAll('.tc').forEach(b=>b.classList.toggle('on',b.dataset.t===S.theme))}
                function font(){S.appFontScale=cl(S.appFontScale);S.widgetFontScale=cl(S.widgetFontScale);document.documentElement.style.fontSize=(16*S.appFontScale)+'px';document.body.style.fontSize=(15*S.appFontScale)+'px';const a=document.getElementById('af'),w=document.getElementById('wf');if(a)a.value=Math.round(S.appFontScale*100);if(w)w.value=Math.round(S.widgetFontScale*100);tx(document.getElementById('afV'),Math.round(S.appFontScale*100)+' %');tx(document.getElementById('wfV'),Math.round(S.widgetFontScale*100)+' %')}
                function themes(){const g=document.getElementById('tg');g.innerHTML='';Object.entries(THEMES).forEach(([id,q])=>{const b=document.createElement('button');b.className='tc';b.type='button';b.dataset.t=id;b.innerHTML='<span class="sw" style="background:linear-gradient(135deg,'+q.a+','+q.s+')"></span><span class="tn">'+q.n[lg()]+'</span>';b.onclick=()=>{S.theme=id;theme();save()};g.appendChild(b)});theme()}
                function staticText(){const t=T();tx(document.querySelector('.header h1'),t.title);const cw=document.getElementById('currentWeekBtn');if(cw){const l=cw.querySelector('b')?.textContent||'A',want=t.thisWeek+' : <b>'+l+'</b>';if(cw.innerHTML!==want)cw.innerHTML=want}document.querySelectorAll('.weekTab').forEach(b=>tx(b,t.week+' '+b.dataset.week));document.querySelectorAll('.nav').forEach(b=>{const sp=b.querySelector('span')?.outerHTML||'',lab=b.dataset.mode==='today'?t.today:(b.dataset.mode==='week'?t.week:t.edit),want=sp+lab;if(b.innerHTML!==want)b.innerHTML=want});tx(document.querySelector('.timelineHead strong'),t.progress);const im=document.getElementById('importPhoto');if(im&&!im.disabled)tx(im,t.importPhoto);document.querySelectorAll('.sectionHead h3').forEach(x=>{const z=x.textContent;if(/interrupt|Unterbrech|Noms/i.test(z))tx(x,t.breaks);else if(/Horaires|Stunden|period|7 heures/i.test(z))tx(x,t.slots)});tx(document.getElementById('addCourse'),'＋ '+t.add);const bn=document.querySelectorAll('.breakName');if(bn[0])tx(bn[0],t.gap);if(bn[1])tx(bn[1],t.lunch);document.querySelectorAll('.badgeToggle').forEach(x=>{const n=[...x.childNodes].find(n=>n.nodeType===3);if(n&&n.nodeValue!==t.badge)n.nodeValue=t.badge});const labs=document.querySelectorAll('#courseForm .field label');if(labs[0])tx(labs[0],t.period);if(labs[1])tx(labs[1],t.group);if(labs[2])tx(labs[2],t.room);tx(document.getElementById('deleteCourse'),t.del);tx(document.getElementById('cancelEdit'),t.cancel);tx(document.querySelector('#courseForm button[type=submit]'),t.save);settingsText()}
                function dynamicText(){const t=T();document.querySelectorAll('.todayCourse.current .badge').forEach(x=>tx(x,t.current));document.querySelectorAll('.todayCourse.gap .label,.gapCell .cellLabel').forEach(x=>tx(x,t.gap));document.querySelectorAll('.todayCourse.lunch .label,.lunchCell .cellLabel').forEach(x=>tx(x,t.lunch));const wh=document.querySelector('.weekTop h2');if(wh){const l=document.getElementById('weekTitleLetter')?.textContent||'A',want=t.weekPreview+' <span id="weekTitleLetter" class="weekLetter">'+l+'</span>';if(wh.innerHTML!==want)wh.innerHTML=want}const c=document.getElementById('editCount');if(c){const n=(c.textContent.match(/\d+/)||['0'])[0];tx(c,n+' '+t.courses)}}
                function settingsText(){const t=T();tx(document.getElementById('sTitle'),t.settings);tx(document.getElementById('pApp'),t.appPreview);tx(document.getElementById('pWidget'),t.widgetPreview);tx(document.getElementById('miniTitle'),t.title);tx(document.getElementById('afT'),t.appFont);tx(document.getElementById('wfT'),t.widgetFont);tx(document.getElementById('lgT'),t.language);tx(document.getElementById('thT'),t.theme);tx(document.getElementById('sReset'),t.reset);tx(document.getElementById('sDone'),t.close)}
                function refresh(){theme();font();staticText();dynamicText()}
                function wrap(name){const f=window[name];if(typeof f!=='function'||f.__pv2)return;const w=function(){const r=f.apply(this,arguments);setTimeout(refresh,0);return r};w.__pv2=true;window[name]=w}
                ['render','renderToday','renderWeek','renderEdit','renderContext','openEditor','updateSlotPreview'].forEach(wrap);

                document.getElementById('settingsBtn').onclick=()=>{m.classList.add('show');document.getElementById('lg').value=lg();themes();font();settingsText()};document.getElementById('sX').onclick=()=>m.classList.remove('show');document.getElementById('sDone').onclick=()=>m.classList.remove('show');m.onclick=e=>{if(e.target===m)m.classList.remove('show')};document.getElementById('af').oninput=e=>{S.appFontScale=Number(e.target.value)/100;font();save()};document.getElementById('wf').oninput=e=>{S.widgetFontScale=Number(e.target.value)/100;font();save()};document.getElementById('lg').onchange=e=>{S.language=e.target.value;themes();refresh();save()};document.getElementById('sReset').onclick=()=>{S={appFontScale:1,widgetFontScale:1,language:'fr',theme:'blue'};document.getElementById('lg').value='fr';themes();refresh();save()};
                window.refreshPersonalizationV2=refresh;refresh();themes();
              }catch(e){console.log('Personalization V2',e)}
            })();
            """;
    }
}
